/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

/**
 *
 * @author Sistema
 */
public class jfrmRegistroRouter extends javax.swing.JDialog {

    /**
     * Creates new form jfrmRegistroRouter
     */
    public jfrmRegistroRouter(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btn_continuar4 = new javax.swing.JButton();
        btn_cancelar4 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        RUC15 = new javax.swing.JLabel();
        txt_nombre8 = new javax.swing.JTextField();
        RazonSocial8 = new javax.swing.JLabel();
        txt_ipadm7 = new javax.swing.JTextField();
        txt_ipaaa7 = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        txt_ipntp7 = new javax.swing.JTextField();
        txt_ipdns7 = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        chb_ssh7 = new javax.swing.JCheckBox();
        txt_dominio7 = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        txt_ipinterface2 = new javax.swing.JTextField();
        txt_btninterface2 = new javax.swing.JButton();
        txt_maskinterface2 = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        jScrollPane22 = new javax.swing.JScrollPane();
        list_interfaces = new javax.swing.JList<>();
        jLabel62 = new javax.swing.JLabel();
        jScrollPane23 = new javax.swing.JScrollPane();
        list_ipinterfaces = new javax.swing.JList<>();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        btn_continuar4.setText("Continuar");
        btn_continuar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_continuar4ActionPerformed(evt);
            }
        });

        btn_cancelar4.setText("Cancelar");
        btn_cancelar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelar4ActionPerformed(evt);
            }
        });

        jPanel13.setBackground(new java.awt.Color(153, 153, 255));

        jLabel61.setText("IP Servidor autenticacion AAA");

        RUC15.setText("Hostname");

        txt_nombre8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombre8ActionPerformed(evt);
            }
        });

        RazonSocial8.setText("IP Dns");

        txt_ipadm7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ipadm7ActionPerformed(evt);
            }
        });

        jLabel63.setText("IP Adminstracion");

        jLabel64.setText("IP Ntp");

        txt_ipntp7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ipntp7ActionPerformed(evt);
            }
        });

        txt_ipdns7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ipdns7ActionPerformed(evt);
            }
        });

        jLabel65.setText("Conexion segura SSH");

        chb_ssh7.setText("Habilitar");

        jLabel66.setText("Dominio de red");

        jLabel67.setText("IP Interface");

        txt_btninterface2.setText("Asignar Ip interface");

        jLabel68.setText("Mask Interface ");

        list_interfaces.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Interafece1", "Interafece2", "Interafece3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane22.setViewportView(list_interfaces);

        jLabel62.setText("Lista de interfaces");

        list_ipinterfaces.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Interafece1 - Ip1 - Mask1", "Interafece2 - Ip2 - Mask2", "Interafece3 - Ip3 - Mask3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane23.setViewportView(list_ipinterfaces);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane22)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(jLabel67)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_ipinterface2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel13Layout.createSequentialGroup()
                                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RazonSocial8)
                                            .addComponent(jLabel64)
                                            .addComponent(jLabel61)
                                            .addComponent(RUC15)
                                            .addComponent(jLabel65)
                                            .addComponent(jLabel63)
                                            .addComponent(jLabel66))
                                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel13Layout.createSequentialGroup()
                                                .addGap(54, 54, 54)
                                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(chb_ssh7)
                                                    .addComponent(txt_ipaaa7, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                                    .addComponent(txt_ipadm7)
                                                    .addComponent(txt_dominio7)
                                                    .addComponent(txt_ipdns7)
                                                    .addComponent(txt_ipntp7)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txt_nombre8, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jLabel62))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(jLabel68)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_maskinterface2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(txt_btninterface2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane23, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombre8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RUC15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chb_ssh7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel65))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ipadm7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_dominio7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel66))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ipdns7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RazonSocial8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ipntp7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel64))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ipaaa7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel61))
                .addGap(18, 18, 18)
                .addComponent(jLabel62)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel67)
                    .addComponent(txt_ipinterface2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel68)
                    .addComponent(txt_maskinterface2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txt_btninterface2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("INGRESE LOS DATOS PARA LA CONFIGURACION DEL ROUTER");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_continuar4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_cancelar4))
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_continuar4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelar4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_continuar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_continuar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_continuar4ActionPerformed

    private void btn_cancelar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cancelar4ActionPerformed

    private void txt_nombre8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombre8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombre8ActionPerformed

    private void txt_ipadm7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ipadm7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ipadm7ActionPerformed

    private void txt_ipntp7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ipntp7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ipntp7ActionPerformed

    private void txt_ipdns7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ipdns7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ipdns7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmRegistroRouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmRegistroRouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmRegistroRouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmRegistroRouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jfrmRegistroRouter dialog = new jfrmRegistroRouter(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CiudadOrigen2;
    private javax.swing.JLabel CiudadOrigen3;
    private javax.swing.JLabel CiudadOrigen4;
    private javax.swing.JLabel CiudadOrigen5;
    private javax.swing.JLabel CiudadOrigen6;
    private javax.swing.JLabel CiudadOrigen7;
    private javax.swing.JLabel CiudadOrigen8;
    private javax.swing.JLabel RUC1;
    private javax.swing.JLabel RUC10;
    private javax.swing.JLabel RUC11;
    private javax.swing.JLabel RUC12;
    private javax.swing.JLabel RUC13;
    private javax.swing.JLabel RUC14;
    private javax.swing.JLabel RUC15;
    private javax.swing.JLabel RUC2;
    private javax.swing.JLabel RUC3;
    private javax.swing.JLabel RUC4;
    private javax.swing.JLabel RUC5;
    private javax.swing.JLabel RUC6;
    private javax.swing.JLabel RUC7;
    private javax.swing.JLabel RUC8;
    private javax.swing.JLabel RUC9;
    private javax.swing.JLabel RazonSocial1;
    private javax.swing.JLabel RazonSocial2;
    private javax.swing.JLabel RazonSocial3;
    private javax.swing.JLabel RazonSocial4;
    private javax.swing.JLabel RazonSocial5;
    private javax.swing.JLabel RazonSocial6;
    private javax.swing.JLabel RazonSocial7;
    private javax.swing.JLabel RazonSocial8;
    private javax.swing.JButton btn_cancelar4;
    private javax.swing.JButton btn_continuar4;
    private javax.swing.JButton btn_vlan1;
    private javax.swing.JButton btn_vlan2;
    private javax.swing.JButton btn_vlan3;
    private javax.swing.JButton btn_vlan4;
    private javax.swing.JButton btn_vlan5;
    private javax.swing.JButton btn_vlan6;
    private javax.swing.JButton btn_vlan7;
    private javax.swing.JCheckBox chb_ssh;
    private javax.swing.JCheckBox chb_ssh1;
    private javax.swing.JCheckBox chb_ssh2;
    private javax.swing.JCheckBox chb_ssh3;
    private javax.swing.JCheckBox chb_ssh4;
    private javax.swing.JCheckBox chb_ssh5;
    private javax.swing.JCheckBox chb_ssh6;
    private javax.swing.JCheckBox chb_ssh7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JList<String> list_interfaces;
    private javax.swing.JList<String> list_ipinterfaces;
    private javax.swing.JList<String> list_ipvlan;
    private javax.swing.JList<String> list_ipvlan1;
    private javax.swing.JList<String> list_ipvlan2;
    private javax.swing.JList<String> list_ipvlan3;
    private javax.swing.JList<String> list_ipvlan4;
    private javax.swing.JList<String> list_ipvlan5;
    private javax.swing.JList<String> list_ipvlan6;
    private javax.swing.JList<String> list_nombrevlans;
    private javax.swing.JList<String> list_nombrevlans1;
    private javax.swing.JList<String> list_nombrevlans2;
    private javax.swing.JList<String> list_nombrevlans3;
    private javax.swing.JList<String> list_nombrevlans4;
    private javax.swing.JList<String> list_nombrevlans5;
    private javax.swing.JList<String> list_nombrevlans6;
    private javax.swing.JList<String> list_vlans;
    private javax.swing.JList<String> list_vlans1;
    private javax.swing.JList<String> list_vlans2;
    private javax.swing.JList<String> list_vlans3;
    private javax.swing.JList<String> list_vlans4;
    private javax.swing.JList<String> list_vlans5;
    private javax.swing.JList<String> list_vlans6;
    private javax.swing.JButton txt_btninterface2;
    private javax.swing.JButton txt_btnvlan2;
    private javax.swing.JButton txt_btnvlan3;
    private javax.swing.JButton txt_btnvlan4;
    private javax.swing.JButton txt_btnvlan5;
    private javax.swing.JButton txt_btnvlan6;
    private javax.swing.JButton txt_btnvlan7;
    private javax.swing.JButton txt_btnvlan8;
    private javax.swing.JTextField txt_cantvlans;
    private javax.swing.JTextField txt_cantvlans1;
    private javax.swing.JTextField txt_cantvlans2;
    private javax.swing.JTextField txt_cantvlans3;
    private javax.swing.JTextField txt_cantvlans4;
    private javax.swing.JTextField txt_cantvlans5;
    private javax.swing.JTextField txt_cantvlans6;
    private javax.swing.JTextField txt_dominio;
    private javax.swing.JTextField txt_dominio1;
    private javax.swing.JTextField txt_dominio2;
    private javax.swing.JTextField txt_dominio3;
    private javax.swing.JTextField txt_dominio4;
    private javax.swing.JTextField txt_dominio5;
    private javax.swing.JTextField txt_dominio6;
    private javax.swing.JTextField txt_dominio7;
    private javax.swing.JTextField txt_ipaaa;
    private javax.swing.JTextField txt_ipaaa1;
    private javax.swing.JTextField txt_ipaaa2;
    private javax.swing.JTextField txt_ipaaa3;
    private javax.swing.JTextField txt_ipaaa4;
    private javax.swing.JTextField txt_ipaaa5;
    private javax.swing.JTextField txt_ipaaa6;
    private javax.swing.JTextField txt_ipaaa7;
    private javax.swing.JTextField txt_ipadm;
    private javax.swing.JTextField txt_ipadm1;
    private javax.swing.JTextField txt_ipadm2;
    private javax.swing.JTextField txt_ipadm3;
    private javax.swing.JTextField txt_ipadm4;
    private javax.swing.JTextField txt_ipadm5;
    private javax.swing.JTextField txt_ipadm6;
    private javax.swing.JTextField txt_ipadm7;
    private javax.swing.JTextField txt_ipdns;
    private javax.swing.JTextField txt_ipdns1;
    private javax.swing.JTextField txt_ipdns2;
    private javax.swing.JTextField txt_ipdns3;
    private javax.swing.JTextField txt_ipdns4;
    private javax.swing.JTextField txt_ipdns5;
    private javax.swing.JTextField txt_ipdns6;
    private javax.swing.JTextField txt_ipdns7;
    private javax.swing.JTextField txt_ipinterface2;
    private javax.swing.JTextField txt_ipntp;
    private javax.swing.JTextField txt_ipntp1;
    private javax.swing.JTextField txt_ipntp2;
    private javax.swing.JTextField txt_ipntp3;
    private javax.swing.JTextField txt_ipntp4;
    private javax.swing.JTextField txt_ipntp5;
    private javax.swing.JTextField txt_ipntp6;
    private javax.swing.JTextField txt_ipntp7;
    private javax.swing.JTextField txt_ipvlan;
    private javax.swing.JTextField txt_ipvlan1;
    private javax.swing.JTextField txt_ipvlan2;
    private javax.swing.JTextField txt_ipvlan3;
    private javax.swing.JTextField txt_ipvlan4;
    private javax.swing.JTextField txt_ipvlan5;
    private javax.swing.JTextField txt_ipvlan6;
    private javax.swing.JComboBox<String> txt_logictipo;
    private javax.swing.JComboBox<String> txt_logictipo1;
    private javax.swing.JComboBox<String> txt_logictipo2;
    private javax.swing.JComboBox<String> txt_logictipo3;
    private javax.swing.JComboBox<String> txt_logictipo4;
    private javax.swing.JComboBox<String> txt_logictipo5;
    private javax.swing.JComboBox<String> txt_logictipo6;
    private javax.swing.JTextField txt_maskinterface2;
    private javax.swing.JTextField txt_maskvlan;
    private javax.swing.JTextField txt_maskvlan1;
    private javax.swing.JTextField txt_maskvlan2;
    private javax.swing.JTextField txt_maskvlan3;
    private javax.swing.JTextField txt_maskvlan4;
    private javax.swing.JTextField txt_maskvlan5;
    private javax.swing.JTextField txt_maskvlan6;
    private javax.swing.JTextField txt_nombre1;
    private javax.swing.JTextField txt_nombre2;
    private javax.swing.JTextField txt_nombre3;
    private javax.swing.JTextField txt_nombre4;
    private javax.swing.JTextField txt_nombre5;
    private javax.swing.JTextField txt_nombre6;
    private javax.swing.JTextField txt_nombre7;
    private javax.swing.JTextField txt_nombre8;
    private javax.swing.JTextField txt_nombrevlan;
    private javax.swing.JTextField txt_nombrevlan1;
    private javax.swing.JTextField txt_nombrevlan2;
    private javax.swing.JTextField txt_nombrevlan3;
    private javax.swing.JTextField txt_nombrevlan4;
    private javax.swing.JTextField txt_nombrevlan5;
    private javax.swing.JTextField txt_nombrevlan6;
    // End of variables declaration//GEN-END:variables
}
